# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://www.github.com/'}
- {icon: 'facebook', link: 'https://www.facebook.com/profile.php?id=100022933771248'}
- {icon: 'envelope', link: 'mailto:508948344@qq.com'}
- {icon: 'qq', link: '//shang.qq.com/wpa/qunwpa?idkey=65bbdf1988be659088afc8f6a0d2b654b50676583eff4d4100982f297360b9f9'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
